###### OOMP FILE  ######

import OOMP
import OOMPtags

newPart = OOMP.oompItem()

newPart.addTag("hexID", "")
newPart.addTag("oompType", "FOOTPRINT")
newPart.addTag("oompSize", "eagle")
newPart.addTag("oompColor", "eagle-default")
newPart.addTag("oompDesc", "ref-packages")
newPart.addTag("oompIndex", "GTS_S-PBGA-N288")
newPart.addTag("oompName", "eagle-default/ref-packages/GTS_S-PBGA-N288")

newPart.addTag("description", """&lt;b&gt;Flip Chip BGA Package&lt;/b&gt; GTS (S-PBGA-N288)&lt;p&gt;&#xD;
Auto generated by &lt;i&gt;make-symbol-device-package-bsdl.ulp Rev. 29&lt;/i&gt;&lt;br&gt;&#xD;
Source: sprm148b.bsd&lt;br&gt;&#xD;
http://focus.ti.com/lit/ug/spru811a/spru811a.pdf""")

newPart = OOMPtags.addTags(newPart,"FOOTPRINT-eagle-eagle-default-ref-packages-GTS_S-PBGA-N288",hexID='',oompType='FOOTPRINT',oompSize='eagle',oompColor='eagle-default',oompDesc='ref-packages',oompIndex='GTS_S-PBGA-N288')

OOMP.parts.append(newPart)