###### OOMP FILE  ######

import OOMP
import OOMPtags

newPart = OOMP.oompItem()

newPart.addTag("hexID", "")
newPart.addTag("oompType", "FOOTPRINT")
newPart.addTag("oompSize", "eagle")
newPart.addTag("oompColor", "eagle-default")
newPart.addTag("oompDesc", "ref-packages")
newPart.addTag("oompIndex", "GHH_S-PBGA-N179")
newPart.addTag("oompName", "eagle-default/ref-packages/GHH_S-PBGA-N179")

newPart.addTag("description", """&lt;b&gt;GHH (S-PBGA-N179)&lt;/b&gt;&lt;p&gt;&#xD;
Auto generated by &lt;i&gt;make-symbol-device-package-bsdl.ulp Rev. 30&lt;/i&gt;&lt;br&gt;&#xD;
Source: sprm155a.bsm&lt;br&gt;&#xD;
http://focus.ti.com/lit/ds/symlink/tms320vc5509a.pdf""")

newPart = OOMPtags.addTags(newPart,"FOOTPRINT-eagle-eagle-default-ref-packages-GHH_S-PBGA-N179",hexID='',oompType='FOOTPRINT',oompSize='eagle',oompColor='eagle-default',oompDesc='ref-packages',oompIndex='GHH_S-PBGA-N179')

OOMP.parts.append(newPart)