###### OOMP FILE  ######

import OOMP
import OOMPtags

newPart = OOMP.oompItem()

newPart.addTag("hexID", "")
newPart.addTag("oompType", "FOOTPRINT")
newPart.addTag("oompSize", "eagle")
newPart.addTag("oompColor", "eagle-default")
newPart.addTag("oompDesc", "ref-packages")
newPart.addTag("oompIndex", "ZKB_S-PBGA-N256")
newPart.addTag("oompName", "eagle-default/ref-packages/ZKB_S-PBGA-N256")

newPart.addTag("description", """&lt;b&gt;sprm328&lt;/b&gt; &lt;font color=&quot;red&quot;&gt;edit this description&lt;/font&gt;&lt;p&gt;&#xD;
Auto generated by &lt;i&gt;make-symbol-device-package-bsdl.ulp Rev. 29&lt;/i&gt;&lt;br&gt;&#xD;
Source: sprm328.bsm""")

newPart = OOMPtags.addTags(newPart,"FOOTPRINT-eagle-eagle-default-ref-packages-ZKB_S-PBGA-N256",hexID='',oompType='FOOTPRINT',oompSize='eagle',oompColor='eagle-default',oompDesc='ref-packages',oompIndex='ZKB_S-PBGA-N256')

OOMP.parts.append(newPart)