###### OOMP FILE  ######

import OOMP
import OOMPtags

newPart = OOMP.oompItem()

newPart.addTag("hexID", "")
newPart.addTag("oompType", "FOOTPRINT")
newPart.addTag("oompSize", "eagle")
newPart.addTag("oompColor", "eagle-default")
newPart.addTag("oompDesc", "ref-packages")
newPart.addTag("oompIndex", "ZUN_SPBGA-N561")
newPart.addTag("oompName", "eagle-default/ref-packages/ZUN_SPBGA-N561")

newPart.addTag("description", """&lt;b&gt;ZUN (S-PBGA-N561)&lt;/b&gt; OLASTIC BALL GRID ARRAY&lt;p&gt;&#xD;
Auto generated by &lt;i&gt;make-symbol-device-package-bsdl.ulp Rev. 29&lt;/i&gt;&lt;br&gt;&#xD;
Source: sprm335.bsd&lt;br&gt;&#xD;
http://focus.ti.com/lit/ds/symlink/tms320c6474.pdf""")

newPart = OOMPtags.addTags(newPart,"FOOTPRINT-eagle-eagle-default-ref-packages-ZUN_SPBGA-N561",hexID='',oompType='FOOTPRINT',oompSize='eagle',oompColor='eagle-default',oompDesc='ref-packages',oompIndex='ZUN_SPBGA-N561')

OOMP.parts.append(newPart)