###### OOMP FILE  ######

import OOMP
import OOMPtags

newPart = OOMP.oompItem()

newPart.addTag("hexID", "")
newPart.addTag("oompType", "FOOTPRINT")
newPart.addTag("oompSize", "eagle")
newPart.addTag("oompColor", "eagle-default")
newPart.addTag("oompDesc", "ref-packages")
newPart.addTag("oompIndex", "ZDH_S-PBGA-N256")
newPart.addTag("oompName", "eagle-default/ref-packages/ZDH_S-PBGA-N256")

newPart.addTag("description", """&lt;b&gt;ZDH (S-PBGA-N256)&lt;/b&gt; PLASTIC BALL GRID ARRAY&lt;p&gt;&#xD;
Auto generated by &lt;i&gt;make-symbol-device-package-bsdl.ulp Rev. 29&lt;/i&gt;&lt;br&gt;&#xD;
Source: http://focus.ti.com/lit/ds/symlink/tms320c6720.pdf""")

newPart = OOMPtags.addTags(newPart,"FOOTPRINT-eagle-eagle-default-ref-packages-ZDH_S-PBGA-N256",hexID='',oompType='FOOTPRINT',oompSize='eagle',oompColor='eagle-default',oompDesc='ref-packages',oompIndex='ZDH_S-PBGA-N256')

OOMP.parts.append(newPart)