###### OOMP FILE  ######

import OOMP
import OOMPtags

newPart = OOMP.oompItem()

newPart.addTag("hexID", "")
newPart.addTag("oompType", "FOOTPRINT")
newPart.addTag("oompSize", "eagle")
newPart.addTag("oompColor", "eagle-default")
newPart.addTag("oompDesc", "ref-packages")
newPart.addTag("oompIndex", "ZCE_S-PBGA-N361")
newPart.addTag("oompName", "eagle-default/ref-packages/ZCE_S-PBGA-N361")

newPart.addTag("description", """&lt;b&gt;ZCE (S-PBGA-N361)&lt;/b&gt;&lt;p&gt;&#xD;
Auto generated by &lt;i&gt;make-symbol-device-package-bsdl.ulp Rev. 30&lt;/i&gt;&lt;br&gt;&#xD;
Source: sprm377a.bsm&lt;br&gt;&#xD;
http://focus.ti.com/lit/ds/symlink/omap-l138.pdf""")

newPart = OOMPtags.addTags(newPart,"FOOTPRINT-eagle-eagle-default-ref-packages-ZCE_S-PBGA-N361",hexID='',oompType='FOOTPRINT',oompSize='eagle',oompColor='eagle-default',oompDesc='ref-packages',oompIndex='ZCE_S-PBGA-N361')

OOMP.parts.append(newPart)