###### OOMP FILE  ######

import OOMP
import OOMPtags

newPart = OOMP.oompItem()

newPart.addTag("hexID", "")
newPart.addTag("oompType", "FOOTPRINT")
newPart.addTag("oompSize", "eagle")
newPart.addTag("oompColor", "eagle-default")
newPart.addTag("oompDesc", "ref-packages")
newPart.addTag("oompIndex", "S-PBGA-N113")
newPart.addTag("oompName", "eagle-default/ref-packages/S-PBGA-N113")

newPart.addTag("description", """&lt;b&gt;PLASTIC BGA 113-BALL&lt;/b&gt; (ZQW)&lt;p&gt;&#xD;
Auto generated by &lt;i&gt;make-symbol-device-package-bsdl.ulp Rev. 19&lt;/i&gt;&lt;br&gt;&#xD;
Source: http://focus.ti.com/docs/prod/folders/print/msp430fg4618.html""")

newPart = OOMPtags.addTags(newPart,"FOOTPRINT-eagle-eagle-default-ref-packages-S-PBGA-N113",hexID='',oompType='FOOTPRINT',oompSize='eagle',oompColor='eagle-default',oompDesc='ref-packages',oompIndex='S-PBGA-N113')

OOMP.parts.append(newPart)